### ISSUE TITLE
CompressonatorCLI -Performance Command Invalid

### ISSUE THREAD

**Issue by BigheadSMZ** [GPUOpen-Tools/compressonator#140]
In older versions I've used the (-Quality) and (-Performance) commands to squeeze out a bit more quality in BC7. But in recent versions it is coming up as an invalid command despite still being included in the built in help. Is this command no longer supported?

The specific error is...
Option [-Performance] : Command option is invalid  Invalid Command

I noticed there is now two "performance" commands, the latter does work.
-Performance <value>         Sets performance of encoding for BC7
-performance                 Shows various performance stats

**Comment by NPCompress** [comment]
@BigheadSMZ  Thanks for reporting this issue, The latest version of code has a change in the way command line parameters are processed, and it seems that this option is missing which would have allowed it to be processed specifically by the BC7 codec and not by a command line applications option.

The fix is in cmdline.cpp where we have a list of supported codec options:
               (strcmp(strCommand, "-NumThreads") == 0) ||
                (strcmp(strCommand, "-Quality") == 0) ||
                (strcmp(strCommand, "-ModeMask") == 0) ||
                (strcmp(strCommand, "-PatternRec") == 0) ||
                (strcmp(strCommand, "-ColourRestrict") == 0) ||
                (strcmp(strCommand, "-AlphaRestrict") == 0) ||
                (strcmp(strCommand, "-AlphaThreshold") == 0) ||
                (strcmp(strCommand, "-ImageNeedsAlpha") == 0) ||
                (strcmp(strCommand, "-UseSSE2") == 0) ||
...
This was missing and added now:
                (strcmp(strCommand, "-Performance") == 0) ||

The fix will be posted along side our next source updates (expected late September).

**Comment by NPCompress** [comment]
@BigheadSMZ This issue has been fixed in the  latest source update!
