### ISSUE TITLE
ASTC quality went down since v2, and is not competitive vs. astcenc

### ISSUE THREAD

**Issue by richgel999** [GPUOpen-Tools/compressonator#161]
Hi,
I compressed an image using an older version of Compressonator (v2 series) to ASTC 8bpp highest quality (q=1.0), and got 40.737 REC 709 Y dB. I then upgraded to the latest version, compressed it again, and got a miserable 34.583 dB.

![image](https://user-images.githubusercontent.com/6934809/105917472-5824b800-6000-11eb-88f6-722d4915300b.png)

astcenc v2.2 gets 45.743. Something seems very wrong with ASTC support in Compressonator. It's quality is too low, and it looks like it's regressed.

**Comment by richgel999** [comment]
Here's the image I've been using for testing, although I doubt it matters much:
![xmen_1024](https://user-images.githubusercontent.com/6934809/105917676-afc32380-6000-11eb-81d6-0f1e22ac7a3c.png)

**Comment by NPCompress** [comment]
@richgel999  Thanks for the notification. Will look into this.

**Comment by solidpixel** [comment]
It's worth noting that the astcenc project has been relicensed since the original released (now Apache 2), and now ships with a clean library interface to the core codec. This makes it much easier to integrate into other projects. 

With the latest release (3.1) it's substantially faster than the original 1.7 series releases (around 17 times faster), so it might be worth swapping to it.

**Comment by denislevesqueAMD** [comment]
ASTC support has been dropped from Compressonator, so this issue is no longer relevant.
