### ISSUE TITLE
Can't save the ASTC to KTX with mip maps levels

### ISSUE THREAD

**Issue by Andreyogld3d** [GPUOpen-Tools/Compressonator#18]
Hello!
How to reproduce
1) Open image in some format (tga)
2) generate mip maps
3) Select ASTC format in Destination options
4) Select KTX in Destination options
5) Process Selected images
We can see in output window:

**Error(0): KTX Plugin ID(1) saving file = some_correct_path/Bush_02_1.KTX 
Error: saving image or format is unsupported**

Note: 
1) If select *.ASTC file extension with mip maps is working fine
2) Without mip maps ASTC to *.ktx  is working fine

**Comment by xooiamd** [comment]
hi! is this issue observed in the latest master branch? i can't reproduce the issue. Can you provide the image that you used to reproduce this issue?  

Thanks.

**Comment by Andreyogld3d** [comment]
Hello xooiamd!
Yes, i'm trying the master branch(Compressonator_2.3.2953.exe) 
It can be any image png, tga. I attached image:
![bush_02](https://cloud.githubusercontent.com/assets/8597425/19779978/17d01f92-9c8c-11e6-8614-16c01ed3286e.png)

**Comment by xooiamd** [comment]
hi @Andreyogld3d , Compressonator_2.3.2953.exe is a binary released on july, after that we have made a few changes including adding in ktx support for mipmap generation. You can refer to the readme "Recent additions and changes since v2.3 release" for the changes we committed in master branch.  So i would recommend you clone the latest master branch with the common lib submodules and build the Compressonator\Applications\CompressonatorGUI in release_md configuration to get the latest Compressonator.exe . Let me know if you have issue in building it. Thanks!

**Comment by Andreyogld3d** [comment]
Hi, xooiamd. Ok,Thanks.

**Comment by Andreyogld3d** [comment]
Hello xooiamd,
i'm trying build the full project CompressonatorGUI, but i have compilation error. I attached 
[output.log:](https://www.dropbox.com/s/tv7nhvewdszjsy3/output.zip?dl=0)

I can't attach zip format via git hub.

**Comment by xooiamd** [comment]
Hi @Andreyogld3d , seems like the compilation failed due to invalid \Common\Lib\ path. Can you check if your common lib folders content is not empty? please note that recently we have moved all our shared common libraries for GPUOpen-Tools (the folders content under Common\Lib\*) to git submodules, the folders content of git submodules will not be downloaded by downloading the zip folder from compressonator repo. You will have to download submodules content from their own repo (for example amd app sdk is in this repo https://github.com/GPUOpen-Tools/common-lib-amd-APPSDK-3.0) or you can do a "git clone --recursive https://github.com/GPUOpen-Tools/Compressonator.git" to get all compressonator content with the submodules content.  Please let me know if you have any further issues. Thanks.

**Comment by Andreyogld3d** [comment]
Hi xooiamd,
I compiled compressonator, now i can save ASCT textures to the KTX with mip maps.
Thanks!
