### ISSUE TITLE
-nomipmap not working for bc6h

### ISSUE THREAD

**Issue by SewerDweller** [GPUOpen-Tools/compressonator#271]
exact command:

`compressonatorcli -fd bc6h -nomipmap -Quality 1.0 src.ktx out.ktx2`

**Comment by denislevesqueAMD** [comment]
@SewerDweller Thanks for the report, we will be looking into this

**Comment by denislevesqueAMD** [comment]
@SewerDweller I've tried this command on my own machine, but I don't see the issue. What did you expect to happen?

The `-nomipmap` option is a manual way of ensuring that mipmap generation is disabled. So when you run the command you have specified you should not see any additional mipmap levels generated in the output image.

**Comment by SewerDweller** [comment]
hey maybe it's because of the input file already containing mip levels. the ktx file I've used can be found here:
https://github.com/SaschaWillems/Vulkan-Assets/blob/a27c0e584434d59b7c7a714e9180eefca6f0ec4b/textures/hdr/pisa_cube.ktx

Ideally I'd want the new file to contain no mipmaps even if the source file has them

**Comment by denislevesqueAMD** [comment]
@SewerDweller Ok, I see what you mean now. An alternative method of doing what you want would be to use the command `compressonatorcli -fd bc6h -miplevels 1 -Quality 1.0 src.ktx out.ktx2`, but it appears that it is currently bugged and doesn't work.

We'll work on fixing the issues so that it works with textures that have existing mipmap levels.

**Comment by NavNTCMP** [comment]
@SewerDweller  Issue addressed in v4.5 release
