### ISSUE TITLE
With OPTION_ENABLE_ALL_APPS OFF there is still a hard dependency on OpenCV

### ISSUE THREAD

**Issue by FilippoLeon** [GPUOpen-Tools/compressonator#276]
When including the project as subdiroectory in CMake and setting
`
	set(OPTION_ENABLE_ALL_APPS OFF)
	set(OPTION_BUILD_CMP_SDK ON)
	set(OPTION_CMP_OPENCV OFF)`

Compressonator requires OpenCV, even though it should be an optional dependency.

**Comment by denislevesqueAMD** [comment]
@FilippoLeon Is the issue that even once you set `OPTION_CMP_OPENCV` to `OFF` it still has OpenCV as a dependency and tries to build with it?

I believe this was fixed in #267, so it should be fine if you pull the latest changes.

Also, we will be changing the default value of `OPTION_CMP_OPENCV` to `OFF` in the next release so you won't need to specify it.

Otherwise, please give a bit more details about the issue you are experiencing.

**Comment by FilippoLeon** [comment]
Hi, yes. Looks exactly what I was looking for. I built the project from the latest stable release. I will try to do so from the main branch,
