### ISSUE TITLE
ETCPACK license

### ISSUE THREAD

**Issue by Chainsawkitten** [GPUOpen-Tools/Compressonator#28]
If I understand the [ETCPACK license](https://github.com/Ericsson/ETCPACK/blob/master/licence.txt) correctly, ETCPACK may only be distributed in binary form, with the exception of `etcdec.cxx`. However, Compressonator distributes `etcimage.cxx` and `etcpack.cxx` (as well as `etcdec.cxx`, which is fine).

Either my understanding of the license is wrong (I don't speak legalese), or this is a problem. Does AMD have an agreement with Ericsson allowing distribution of the source of those files? If so, how should I as a user relate to this? If I click on Fork, do I violate ETCPACK's license since I'm setting up a repository which distributes these files and I'm not covered by such an agreement?

Could a submodule be a solution? Then these files would not be distributed by this repository, strictly speaking, but by Ericsson's repository.

**Comment by NPCompress** [comment]
Thank you for your attention to the ETCPACK License. 

According to our understanding, the license permits distributions **including** binary form, not **only** binary form as you understood. We have followed ETCPACK license by clone it open source unmodified.

Your suggestion to move it to a submodule would help in getting the latest updates and patches.

Since we have open sourced Compressonator in April 2016 prior to ETCPACK license publication in May 2016, we will now include it in Compressonator repository, thanks to your report.

**Comment by Chainsawkitten** [comment]
`etcpack.cxx` does not appear to be unmodified. At least the `#ifdef USE_IN_COMPRESSONATOR` around the `int main`-definition looks suspiciously like something added in Compressonator. (The clue is in the define name.)

**Comment by NPCompress** [comment]
Good point, There are modifications in order remove compiler warnings and to add the lib to another application with a duplicated main() entry!
