### ISSUE TITLE
README: mention dependecy to Qt "imageformats" plugins

### ISSUE THREAD

**Issue by nicomgd** [GPUOpen-Tools/Compressonator#3]
To have the `CompressonatorCLI` understand some image formats, it should have access to Qt image plugins, which are locate in `Common\Lib\Ext\Qt\5.5\plugins`.

Manually copying the `imageformats` from Common to CompressonatorCLI's `plugins` folder does the job.

**Comment by xooiamd** [comment]
hi, we did list that we will need the content of Common/Lib/Ext/Qt/5.5/ in the readme. Thanks.

**Comment by NPCompress** [comment]
Thanks nicomgd
In order to support image formats not supported by default with Qt and the CLI or GUI applications, as you have noted. Users will have to copy over the required 3rd party plug-in DLLs into the Compressonator plugins folder. We will add a note in the read me to help users with similar requirements.
