### ISSUE TITLE
 RGB -> BC1 is swiveled incorrectly

### ISSUE THREAD

**Issue by TrianglesPCT** [GPUOpen-Tools/Compressonator#31]
It seems that using input textures in RGB or RGBA(CMP_FORMAT_RGBA_8888) format, with an output of BC1 will swivel the blue and red channels, resulting in a BC1 texture in BGR format.

If I swivel my input textures data so that it is instead BRGA, and set format to CMP_FORMAT_BGRA_8888, it will produce the correct output, a BC1 texture in RGB format.

Also using an input of CMP_FORMAT_BGR_888 appears to break things, as this produces a completely black BC1 output texture.

Options I'm setting:

	CMP_CompressOptions options;
	memset(&options, 0, sizeof(options));

	options.bDXT1UseAlpha = false;
	options.bDisableMultiThreading = false;
	options.dwSize = sizeof(options);
	options.fquality = 1.0;

	options.nCompressionSpeed = CMP_Speed_Normal;
	options.bUseAdaptiveWeighting = true; //not sure what this does..
	options.fWeightingBlue = 0.082;
	options.fWeightingRed = 0.3086;
	options.fWeightingGreen = 0.6094;	
	options.bUseChannelWeighting = true;

Input Format:
       CMP_Texture input:
	input.dwSize = sizeof(CMP_Texture);
	input.dwHeight = width_height;
	input.dwWidth = width_height;

	input.format = CMP_FORMAT_RGBA_8888;
	input.nBlockDepth = 1;
	input.nBlockHeight = 4;
	input.nBlockWidth = 4;
	input.pData = const_cast<u8*>(uncompressed);
	input.dwDataSize = width_height*width_height * nChannelsInInput;
	input.dwPitch = width_height * nChannelsInInput;

Output Texture:
        CMP_Texture output;
	output.dwSize = sizeof(CMP_Texture);
	output.dwHeight = width_height;
	output.dwWidth = width_height;
	output.dwDataSize = width_height*width_height * BitsPerPixel /8;
        output.format = CMP_FORMAT_BC1;

	output.nBlockDepth = 1;
	output.nBlockHeight = 4;
	output.nBlockWidth = 4;
	output.dwPitch = width_height *BitsPerPixel/8;

**Comment by NPCompress** [comment]
The issue is the same as reported in issue 15

Typical input source is RGBA from our Texture loaders, which are been swizzled as needed when processed according to the target format 

- Codec for BC1 through BC5 are expecting input BGR (BGRA) 
- BC6H, BC7 are expecting input RGBA

There are a number of swizzle flag options and channel mapping functions provided in the code as work around for this, some portions of the code use Compiler Directives USE_SWIZZLE and new code development which is to fix the source input based on destination formats under a "not" USE_OLD_SWIZZLE directive. (Currently disabled on release).

Proper fix would be to adjust all codecs (BC1 to BC5, etc..) to source RGBA. How ever since many users are already performing the swizzle in there code. They will have to adjust again when this is changed!

**Comment by NPCompress** [comment]
We are looking into the issue you noted as:
"CMP_FORMAT_BGR_888 appears to break things, as this produces a completely black BC1 output texture"

Thanks for bringing these issues this to our attention

**Comment by xooiamd** [comment]
hi, please try the latest commit change in the master branch,  it should fix the input of CMP_FORMAT_BGR_888 break issue. Thanks.
