### ISSUE TITLE
Eventual std::bad_alloc when USE_TRACE_WITH_DYNAMIC_MEM is defined

### ISSUE THREAD

**Issue by TrianglesPCT** [GPUOpen-Tools/Compressonator#32]
In the BC7 compressor function void Quant_Init(void) if USE_TRACE_WITH_DYNAMIC_MEM  is defined I am getting std::bad_alloc exception thrown.

  I'm compressing ~1000 images each with 9-12 mip levels, after about 10-20 images it will throw this exception unless I comment out USE_TRACE_WITH_DYNAMIC_MEM 

It appears to be throwing from one of these lines(debugger is showing wrong line but it is near this)

            #ifdef USE_TRACE_WITH_DYNAMIC_MEM
                amd_codes[ numClusters][ numEntries ]    = new int[ MAX_TRACE ];
                amd_trs[ numClusters ][ numEntries ]    = new TRACE[ MAX_TRACE ];
            
                assert(amd_codes[ numClusters][ numEntries ]);
                assert(amd_trs[ numClusters ][ numEntries ]);
            #endif

**Comment by NPCompress** [comment]
The system is running out of memory due to too many Quant_Init(void)  calls or Images loaded for processing at one time. Make sure Quant_Init(void)  is called only once, then closed with Quant_DeInit()! and Image processing is done with multiple threads enabled. If this issue persists we can investigate further.

g_Quant_init counter guards were added to prevent multiple calls to Quant_Init(void)  calls when multithreading!!

Commenting out USE_TRACE_WITH_DYNAMIC_MEM helps pre allocate the ramps used in BC7 and BC6H codecs. But it will keep that memory until all codecs are done. This will work well for systems with large amount of memory available for processing and avoids such errors.

Is your code running on 64Bit or 32 Bit OS?

**Comment by TrianglesPCT** [comment]
The program is running in 64 bit mode.

I'm not actually calling Quan_init() myself, I'm just calling CMP_ConvertTexture(), which appears to call Quan_init every time.  I call this function once for each mip level. With 1000 textures and ~10 mips each, about 10,000 times.

 Also all of my calls to CMP_ConvertTexture are coming from a single thread, one a time, it is only operating on one image at a time.

 The only other API call I make to Compressonator is calling CMP_InitializeBCLibrary once prior to using the BC7 compressor.

**Comment by NPCompress** [comment]
Something seems to be out of place in the initialization sequence. 

When using BC7 with low level calls (where user supplies source 4x4 Image blocks for processing) , one needs to call  CMP_InitializeBCLibrary() once prior to CreateBC7Encoder() and multiple calls to  CMP_EncodeBC7Block() or CMP_DecodeBC7Block( ), then followed by CMP_DestroyBC7Encoder() and finally clean up is done with a single call to CMP_ShutdownBCLibrary()

When using CMP_ConvertTexture() there is no need to call CMP_InitializeBCLibrary()  prior and  CMP_ShutdownBCLibrary() after.

**Comment by NPCompress** [comment]
FYI - There was a fix posted for a memory leak in Quant_DeInit function today.
