### ISSUE TITLE
Blocky alpha in BC7

### ISSUE THREAD

**Issue by ivanassen** [GPUOpen-Tools/Compressonator#62]
Original:
![hammer_pumpkin](https://user-images.githubusercontent.com/378459/51263355-c7508600-19bc-11e9-98f3-4a56e2e04f2a.png)
Compressonator:
![hammer_pumpkin_compressonator](https://user-images.githubusercontent.com/378459/51263353-c6b7ef80-19bc-11e9-98a7-65597858fed8.png)
ISPC:
![hammer_pumpkin_ispc](https://user-images.githubusercontent.com/378459/51263354-c7508600-19bc-11e9-95be-eb31a4733d05.png)

See the attached files.
the _compressonator and _ispc versions are compressed/decompressed by ispc_texcomp and Compressonator, respectively.
The alpha channel produced by Compressonator is much more blocky, to the extent that the defects are visible when blended.

Note that this image has (wrongly) a lot of color detail in areas where the alpha channel is black. Unfortunately this is very hard for artists to fix, because Photoshop treats alpha in its own peculiar way; they never see what's under the "black" alpha, so they can't paint it over with black.

Maybe ISPC_texcomp assumes that the alpha channel will be used for alpha blending, and multiplies the importance of the RGB values by the alpha value, thus "paying more attention" to the alpha channel in the area of transition around the weapon? While Compressonator tries to preserve the (ultimately useless after alphablending) RGB pixels, and sacrifices alpha?

(Note that something went wrong with gamma/SRGB when compressing/decompressing with ISPC - the overall brightness should be the same for all images)

**Comment by NPCompress** [comment]
@ivanassen 
Thank you for bring this to our attention. We will run an analysis on the attached samples and report back to you ASAP.  

What were the settings you used for compressing the original sample with Compressonator and for ISPC_texcomp (this will help us compare the code path used by both application during processing)?

**Comment by ivanassen** [comment]
Oh - sorry I forgot these.
For ISPC_texcomp, I ran the GUI sample and chose the slowest alpha BC7 format from the combo box.
For Compressonator, I used "-fd BC7 -Quality 1.0" on the command line.
(Acceptable ranges and default values for this and other parameters would be much appreciated in the command-line and HTML help - I only found them out from a PDF somewhere.)

**Comment by NPCompress** [comment]
@ivanassen 

![cmp_alpha_channel](https://user-images.githubusercontent.com/18406717/51396888-04785d80-1b0e-11e9-924f-9a897a0c0692.png)
![cmp_imagediff](https://user-images.githubusercontent.com/18406717/51396889-0510f400-1b0e-11e9-8561-fe8a6bb78d67.png)
![ispc_alpha_channel](https://user-images.githubusercontent.com/18406717/51396890-0510f400-1b0e-11e9-8618-e55f7f2c8b53.png)
![ispc_imagediff](https://user-images.githubusercontent.com/18406717/51396891-0510f400-1b0e-11e9-9505-ad4975a750ea.png)
![original_image_alpha_channel](https://user-images.githubusercontent.com/18406717/51396892-0510f400-1b0e-11e9-8c5d-6ad2e7121aee.png)
![original_image_rgb_channels](https://user-images.githubusercontent.com/18406717/51396893-05a98a80-1b0e-11e9-92fd-c10a9ecea3d9.png)

An analysis of the supplied images shows the following result:

The original image alpha channel is shown alongside decompressed images alpha channels generated by both Compressonator (CMP) and ISPC applications. It is noted that there are minor blocking artifacts generated by  Compressonator on the outer rim of the sample. 

Additional updates to our BC7 codec will be applied to minimize these artifacts.

The resulting decompressed images should be as close to the original source image channel formats as possible (RGBA). An analysis run by our Compressonator GUI tool is also attached, showing the respective image differences, SSIM and PSNR values of the resulting decompressed images. There are unaccountable losses in quality observed in the sample supplied (as you noted) for ISPC SSIM 0.753, PSNR 18.7 dB compared to Compressonator SSIM 0.9899 PSNR 40.2 dB, this may be due to some additional processing of the source image prior to compression by ISPC application, but it’s uncertain without an in depth review of the ISPC code.

**Comment by NPCompress** [comment]
@ivanassen
Further testing was performed using additional command line options to get improved results, where the outer alpha channels of the sample has reduce blocking and improved SSIM , PSNR for the image

Two sample tests using the following command line options for analysis were done: (-log is used to generate a text log file with source, destination image analytics )

Using ModeMask = 0xCF
**Compressonator -log -ModeMask 207 -fd BC7  Issue62_original.png  Issue62_bc7_cf.dds**

Using ModeMask = 0xFF
**Compressonator -log -ModeMask 255 -fd BC7  Issue62_original.png  Issue62_bc7_ff.dds**

The process_results.txt file generated the following log:

CompressonatorCLI Performance Log v1.0

Source       : Issue62_original.png, Height 160, Width 124, Size 0.078 MBytes
Destination  : Issue62_bc7.dds
Using        : CPU
Quality      : 0.05
Processed to : BC7        with  1 iteration(s) in 0.232 seconds
MSE          : 8.07
PSNR         : 39.1
SSIM         : 0.9874
Total time   : 0.238 seconds

--------------
Source       : Issue62_original.png, Height 160, Width 124, Size 0.078 MBytes
Destination  : Issue62_bc7.dds
Using        : CPU
Quality      : 0.05
Processed to : BC7        with  1 iteration(s) in 0.266 seconds
MSE          : 6.47
PSNR         : 40.0
SSIM         : 0.9904
Total time   : 0.272 seconds

--------------

Notice the improvement in SSIM and PSNR for ModeMask = 0xFF

![issue62_modemask_ff](https://user-images.githubusercontent.com/18406717/51611913-580ff000-1eee-11e9-94b8-3fef70bdd7d1.PNG)

In order to understand why this resulted in improvement, a more detailed explanation of the command line options is provided.

BC7 Encoder Options

BC7 has the following mode settings as shown in the following table
![table1](https://user-images.githubusercontent.com/18406717/51612254-13d11f80-1eef-11e9-936f-0fc892a40311.PNG)

Compressonator uses the following command line options to selectively enable or disable each of these modes when encoding a tile 4x4 RGBA:8888 pixel block

![table2](https://user-images.githubusercontent.com/18406717/51612393-5dba0580-1eef-11e9-8da3-e134c4cb9a35.PNG)

Each pixel in the tile is checked for alpha values, if any alpha value in the input block is set below 255 (blockNeedsAlpha = TRUE) or is a value of {0 or 255} (blockAlphaZeroOne = TRUE), respective modes will be either be kept or discarded using the ModeMask as a guide and the following conditions for each block the Mode cycles from 0 to 7.

If (Mode bit is set in **ModeMask**) then use the mode for processing the source tile 

If the block needs alpha and this mode doesn't support alpha then indicate that this is not a valid mode for the block:
if (blockNeedsAlpha == TRUE) and (Mode has NO ALPHA) then that Mode is disabled from been used for processing

Optional user restriction for colour-only blocks so that they don't use modes that have combined colour+alpha – this avoids the possibility that the encoder might choose an alpha other than 255 (due to parity) and cause something to become accidentally slightly transparent it's possible that when encoding 3-component texture applications will assume that the 4th component can safely be assumed to be 255 all the time

if (blockNeedsAlpha == TRUE) and (Mode has COMBINED ALPHA) and (**ColourRestrict** == TRUE) then that Mode is excluded for processing


Optional restriction for blocks with alpha to avoid issues with punch-through or threshold alpha encoding:

if (blockNeedsAlpha == TRUE) and (Mode has COMBINED ALPHA) and (**AlphaRestrict** == TRUE) and (blockAlphaZeroOne == TRUE) then that Mode is excluded for processing
