### ISSUE TITLE
SDK textures oriented suggested enhancements

### ISSUE THREAD

**Issue by thesmallcreeper** [GPUOpen-Tools/Compressonator#68]
Having experimented with Compressonator GUI I decided to choose its SDK to help me build mipmaps for my Vulkan project on the fly. However feels like SDK (and its examples) does not expose the full capability that GUI-CLI has. Such as:

- `CMP_ConvertTexture` does not support easy mipmap chain creation, only compression/decompression. You cannot create destination texture with different width*height than original. Also a mipmaps creation example would be nice.
- `DDS_Helpers.h/.cpp` maybe should be moved from examples into Source/Header in order to provide a standard way to cache/save mipmaps.
- `DDS_Helpers.h` does not have support for BC6H and BC7. (manage to add BC7 by finding the dwFourCC 'magic number' using debugger, did not pull request because I think you may have a better way to do it in order to keep code clean)
- Also clone SDK might should become more lightweight. All the repo is more less 1GB, something bad for sharing if you want to use SDK as a submodule

Ofcourse I understand that if I get my hands dirty I can -for example- create mipmaps using the functions that GUI-CLI use. However, I believe that both you and the users of the SDK want a easy-to-use SDK and this is why I am writing this issue.

Thank you and have a nice day! <3

**Comment by NPCompress** [comment]
@thesmallcreeper 
Thank you for your support and comments. 

V3.2 release is addressing these issues and will contain a more stream lined SDK with mipmap interfaces (issue#66) and smaller footprint of code (issue#58).

Your suggestion to update the examples  DDS source can be replaced by the Plugins DDS code which is located under Compressonator\Applications\_Plugins\CImage\DDS  that fully supports BC6H and BC7, that code can be moved into the SDK  source.

The repository layout will be sectioned so that the SDK and Applications (CLI , GUI and Tools ) are more manageable.

**Comment by thesmallcreeper** [comment]
Dude you are awesome <3

Btw looking at Cmake file located at Compressonator/Make getting rip off external dependencies (especially at Linux) might also be helpful. (but if I understand correctly this is in your plan for the next release)

Waiting for the next release, hope you easy coding without bugs :)

**Comment by thesmallcreeper** [comment]
Also maybe support for 8-bit sRGB format would be helpful :)

**Comment by giordi91** [comment]
Do you have a rough ETA for the V3.2 release?

**Comment by thesmallcreeper** [comment]
@NPCompress Bro nice job. Have a nice x-mas (without codes in your head) :P <3
