### ISSUE TITLE
DDS Cubemap compress

### ISSUE THREAD

**Issue by AlvaroBarua** [GPUOpen-Tools/Compressonator#69]
Hi,
I was wondering if cubemap compression will be added in a future release.
Right now I am using CMFTStudio for generating irradiance maps and related maps which output either RGBA16 or RGBA32 dds cubemaps and was trying to compress them to BC6H but it always fails, so I am assuming there is no cubemap support in the current state.

Is this planned or should I contribute to it myself? Which I am willing to do since I think is something very useful that is missing from this really amazing tool.

Cheers

**Comment by NPCompress** [comment]
@AlvaroBarua 
The cube map structure formats are in place (MIPS.cpp MipSet structure  m_nDepth settings under TestureType TT_CubeMap and TT_VoulumeTexture) but the code is not fully implemented. It is highly encouraged that users contribute to this tool. Out KTX plugin also has a partial implementation.

Please contribute so that all can benefit.
