### ISSUE TITLE
"Invalid Command Line" on CLI in PowerShell and Command Prompt

### ISSUE THREAD

**Issue by Malkierian** [GPUOpen-Tools/compressonator#71]
And that's all I get.  There is a flash of a few prompts before that, but it's too fast to be able to see.  I'm running the latest release, 4064, and I even tested it with the GUI's "Export to batch", and copying that into both a PS and a Command prompt.  And seeing that it had the arguments after the paths, and the online docs say to put the arguments before the paths, I switched them in the output from "Export to batch" and ran it again.  Outcome is no different in all cases.  This is regardless of whether the PS/Command prompt is run with admin rights or not.

**Comment by Malkierian** [comment]
Both were installed, yes, but no, the CLI was not in the path.  Is that actually necessary? I was providing the literal path to the CLI when calling it. It was running, it wasn't saying that it couldn't find the executable. By the way, the GUI worked just fine.

**Comment by Malkierian** [comment]
![image](https://user-images.githubusercontent.com/774771/57393514-1bec5c80-7178-11e9-94de-4eda93ac0ca5.png)
Also, just want to say, I have never seen this before (4 hours from now?)

**Comment by tinglei1105** [comment]
Hi, has this issue been solved? I met the same problem on my Windows laptop when I run the latest version of CLI in PowerShell. 

![image](https://user-images.githubusercontent.com/26117796/213473650-dcf96ef9-0cef-471f-bd91-6afea28f03a6.png)

**Comment by denislevesqueAMD** [comment]
@tinglei1105 @Malkierian 
As far as I know, this isn't necessarily a Compressonator issue. It seems like an issue with the environment/installation on the computer, which causes Windows to display this error.

None of us have been able to reproduce this error on our own machines. If you have more specific information about the installation that might point to a cause that would be appreciated.

I managed to find this page: https://answers.microsoft.com/en-us/windows/forum/all/how-to-fix-a-start-up-boot-time-command-line-error/2217d776-7a2e-4642-9ed5-ea9eaa5ada49 Which might have information that could help you. Otherwise, I would recommend completely uninstalling and reinstalling Compressonator to see if it fixes the issue.

**Comment by NPCompress** [comment]
@tinglei1105 @Malkierian This issue is been closed as fixed based on previous comment.
