### ISSUE TITLE
Low Quality/Broken ASTC Compression

### ISSUE THREAD

**Issue by YorickCobb** [GPUOpen-Tools/Compressonator#91]
Tested on Compressonator GUI v. 3.2.4691, as well as a few earlier releases.

Set to an 8bpp codec block size (4x4 pixels) and with quality at 1, which should produce maximum-quality ASTC compression, Compressonator's output is noticeably worse than other compression tools. Comparing it to the output of Mali TCT at ~medium settings (6x5 pixel block size, 4.27bpp, 'medium' quality), the difference is night-and-day:

![2020-01-24](https://user-images.githubusercontent.com/52218417/73092536-cfce7d00-3eaa-11ea-9cb9-7f4ae55f5c13.png)

Compressonator at max quality compresses the image much faster than Mali TCT does, which makes me think that the quality setting between 0 and 1 in Compressonator may not be correctly applied?

Also, it seems that when the bitrate is set to anything other than 8bpp (codec block larger than 4x4) the image is completely broken:

![Corrupted ASTC](https://user-images.githubusercontent.com/52218417/73093019-ae21c580-3eab-11ea-947f-693c61489682.png)

**Comment by NPCompress** [comment]
@YorickCobb  Thanks for bringing this to our attention.
We will review the codec and the setup for blocks larger than 4x4.

**Comment by NPCompress** [comment]
@YorickCobb, Issue has been resolved and fixed in the master branch. 

Corrupted block for larger block processing was due to block sizes not been set before processing, it always defaulted to 4x4 source blocks, fix is in cmdline.cpp 

        g_MipSetIn.m_nBlockWidth  = g_CmdPrams.BlockWidth;
        g_MipSetIn.m_nBlockHeight = g_CmdPrams.BlockHeight;
        g_MipSetIn.m_nBlockDepth  = g_CmdPrams.BlockDepth

The quality issue has also been updated to new defaults in ASTC_Host.cpp for:
       plimit_autoset
       oplimit_autoset
       mincorrel_autoset
       dblimit_autoset_2d
       bmc_autoset
       maxiters_autoset

these settings are segmented into process blocks, each calculates a final setting based on a single user quality setting.

These settings can be further optimized, and users are encouraged to provide feedback on other optional ways to set them, that best suites there need.
